---
variables:
  environ: "staging"
stages:
  - lint
  - deploy
  - verify

ansible lint:
  stage: lint
  image:
    name: "cytopia/ansible-lint"
    entrypoint: [""]
  except:
    - main
  only:
    - merge_requests
    - pushes
  before_script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
    - export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=1000
    - export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=1000
    - export no_proxy="localhost,127.0.0.1,172.25.74.47"
    - python3 -m pip install requests
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
  script:
    - ansible-galaxy -vvv collection install -r collections/requirements.yml
    - ansible-lint -p build.yml

deploy_on_stage:
  stage: deploy
  image:
    name: "cytopia/ansible"
    entrypoint: [""]
  except:
    - main
  only:
    - merge_requests
    - pushes
  before_script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
    - export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=1000
    - export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=1000
  script:
    - ansible-playbook --version
    - ansible-galaxy -vvv collection install -r collections/requirements.yml
    - ansible-playbook -i hosts.stage.yml build.yml --vault-password-file .vault_pass

verify_on_staging:
  stage: verify
  image:
    name: "cytopia/ansible"
    entrypoint: [""]
  except:
    - main
  only:
    - merge_requests
    - pushes
  before_script:
    - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
  script:
    - sleep 10
    - ansible-playbook --version
    - ansible-galaxy -vvv collection install -r collections/requirements.yml
    - ansible-playbook -i hosts.stage.yml verify.yml  --vault-password-file .vault_pass -vvvv

# deploy_on_prod:
#   stage: deploy
#   image:
#     name: "cytopia/ansible"
#     entrypoint: [""]
#   only:
#     - main
#   before_script:
#     - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
#     - export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=1000
#     - export ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=1000
#   script:
#     - ansible-playbook --version
#     - ansible-galaxy -vvv collection install -r collections/requirements.yml
#     - ansible-playbook -i hosts.prod.yml build.yml --vault-password-file .vault_pass

# verify_on_prod:
#   stage: verify
#   only:
#     - main
#   before_script:
#     - echo $ANSIBLE_VAULT_PASSWORD > .vault_pass
#   script:
#     - sleep 10
#     - ansible-playbook --version
#     - ansible-galaxy -vvv collection install -r collections/requirements.yml
#     - ansible-playbook -i hosts.prod.yml verify.yml  --vault-password-file .vault_pass
