---

# Delete Policies
#
# -----------------------------------------------------------------------------
- name: Delete All Telemetry Policies
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric.name }}" 
    state: deleted
    deploy: true
    config:
      - name: template_telemetry_feature
      - name: template_telemetry
      # - name: POLICY-121130

      - switch:
        - ip: "{{ device_leaf1 }}"
  vars:
      ansible_command_timeout: 90
      ansible_connect_timeout: 90

- name: Query Policies To Ensure They Are Removed
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric.name }}" 
    state: query
    deploy: true
    config:
      - name: template_telemetry_feature
      - name: template_telemetry
      - name: ntp_server
      - switch:
        - ip: "{{ device_leaf1 }}"
  register: result

- name: Display Query Result
  debug: msg="{{ result['response'] }}"