---

- name: Create an NTP Server using the ntp_server NDFC template
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric.name }}"
    state: merged
    config:
      - name: create_vlan
        create_additional_policy: false
        priority: 4
        policy_vars:
          VLAN: 55
          NAME: Created_W_Ansible

      - switch:
          - ip: "{{ device_leaf1 }}"
  vars:
      ansible_command_timeout: 60
      ansible_connect_timeout: 60
