---
- name: current vpc config
  debug:
    msg: "{{ item.name }} of switch {{ item.switch }}"
  loop: "{{ interface.vpc }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create a vPC interface between leaf1 and leaf2
  dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.vpc }}"
  tags:
    - interface
    - vpc

- name: current loopback config
  debug:
    msg: "{{ item.name }} of switch {{ item.switch }}"
  loop: "{{ interface.loopback }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create a Loopback interface on leaf1 and leaf2
  dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.loopback }}"
  tags:
    - interface
    - loopback
