---
- name: reset | delete loopback interfaces from {{ fabric }}
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.loopback }}"
    state: deleted
  when: interface.loopback != []
  tags:
    - interface

- name: reset | delete vPCs on leaf1 and leaf2 from {{ fabric }}
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.vpc }}"
    state: deleted
  when: interface.vpc != []
  tags:
    - interface

- name: reset | delte routed interfaces from {{ fabric }}
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.routed }}"
    state: deleted
  when: interface.routed != []
  tags:
    - interface

- name: reset | delete sub-interfaces from {{ fabric }}
  cisco.dcnm.dcnm_interface:
    fabric: "{{ fabric.name }}"
    config: "{{ interface.sub_int }}"
    state: deleted
  when: interface.sub_int != []
  tags:
    - interface
