---
# Main NDFC Ansible Playbook
#
#
- hosts: ndfc
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # This testcase field can run any test in the tests directory for the role
    testcase: query
    ndfc_fabric_name: CL-DEVWKS-3310
    # ansible_it_fabric: Test
    controller_version: 11
    ansible_sw1_int1: Ethernet1/4
    ansible_sw1_int2: Ethernet1/5

  roles:
    - template_policy
  
  # tasks:

  # - name: Test J2 temp
  #   vars:
  #     serialno: "{{ item }}"
  #   template:
  #     src: json_data.j2
  #     dest: /home/cisco/CiscoLive/DEVWKS-3310/cisco-live-2022/ansible/file.txt
  #   loop:
  #     - 92CJF95CZLG
  #     - 92CJF95CZL8


    # - name: Test
    #   vars:
    #     payload:
    #       serialNumber: "{{ item }}"
    #       role: "leaf"
    #   cisco.dcnm.dcnm_rest:
    #     method: POST
    #     path: /appcenter/cisco/ndfc/v1/lan-fabric/rest/control/switches/roles
    #     json_data: "[{{ payload | to_json }}]"
    #   loop:
    #     - 92CJF95CZLG
    #     - 9SC6TMSPNV1

  #   - set_fact:
  #       method: GET

  #   - set_fact:
  #       rest_path: "/appcenter/cisco/ndfc/v1/lan-fabric/rest/control/fabrics/{{ ndfc_fabric_name }}"

  #   - name: Test dcnm_rest module
  #     cisco.dcnm.dcnm_rest:
  #       method: "{{ method }}"
  #       path: "{{ rest_path }}"
  #       # json_data: "{{ data }}"
  #     register: result

    # - name: Query fabric
    #   cisco.dcnm.dcnm_inventory:
    #     fabric: "{{ ndfc_fabric_name }}"
    #     state: query
    #   vars:
    #       ansible_command_timeout: 1000
    #       ansible_connect_timeout: 1000