---

- name: Create New Fabric VRFs and attach to leaf1 and leaf2
  cisco.dcnm.dcnm_vrf:
    fabric: "{{ ndfc_fabric_name }}"
    state: merged
    config:
    - vrf_name: VRF_RED
      vrf_id: 9008011
      vrf_template: Default_VRF_Universal
      vrf_extension_template: Default_VRF_Extension_Universal
      vlan_id: 2000
      attach:
        - ip_address: "{{ staging_leaf1 }}"
          deploy: true
        - ip_address: "{{ staging_leaf2 }}"
          deploy: false
    - vrf_name: VRF_GREEN
      vrf_id: 9008012
      vrf_template: Default_VRF_Universal
      vrf_extension_template: Default_VRF_Extension_Universal
      attach:
        - ip_address: "{{ staging_leaf1 }}"
        - ip_address: "{{ staging_leaf2 }}"

- name: Add New Networks to the Fabric
  cisco.dcnm.dcnm_network:
    fabric: "{{ ndfc_fabric_name }}"
    state: overridden
    config:
    - net_name: ansible-netwk-55
      vrf_name: VRF_RED
      net_id: 7005
      net_template: Default_Network_Universal
      net_extension_template: Default_Network_Extension_Universal
      vlan_id: 150
      gw_ip_subnet: '192.168.30.1/24'
      attach:
      - ip_address: "{{ staging_leaf1 }}"
        ports: [Ethernet1/13, Ethernet1/14]
        deploy: true
      - ip_address: "{{ staging_leaf2 }}"
        ports: [Ethernet1/13, Ethernet1/14]
        deploy: true
      deploy: true
    - net_name: ansible-netwk-56
      vrf_name: VRF_GREEN
      net_id: 7002
      net_template: Default_Network_Universal
      net_extension_template: Default_Network_Extension_Universal
      vlan_id: 151
      gw_ip_subnet: '192.168.40.1/24'
      attach:
      - ip_address: "{{ staging_leaf1 }}"
        ports: [Ethernet1/11, Ethernet1/12]
        deploy: true
      - ip_address: "{{ staging_leaf2 }}"
        ports: [Ethernet1/11, Ethernet1/12]
        deploy: true
      deploy: false